### PR TITLE
MAINT: Changed imports from q2-types-genomics to q2-types.

### PR DESCRIPTION
**Pull request by VinzentRisch**
- Changed all imports from q2-types-genomics to q2-types.
- Blocked by https://github.com/qiime2/q2-types/pull/309
- Solves #7

### CODE REVIEW

**Comment by VinzentRisch** [comment]
I could not run the action `evaluate-bins`.
when running 
```
qiime checkm evaluate-bins --i-bins /Users/rischv/Documents/data/MAG/input/mags.qza --p-db-path /Users/rischv/Downloads/checkm_data_2015_01_16 --o-visualization /Users/rischv/Downloads/report.qzv
```
i get this error

Running external command line application(s). This may print messages to stdout and/or stderr.
The command(s) being run are below. These commands cannot be manually re-run as they will depend on temporary files that no longer exist.

Command: checkm lineage_wf -x fasta /var/folders/nj/rfpdzc_90zl3555cttz236_w0000gp/T/qiime2/rischv/data/0a7a97fc-f0f3-462f-880b-66bc9d052fbc/data/sample1 /var/folders/nj/rfpdzc_90zl3555cttz236_w0000gp/T/tmpf022r1r3/results/sample1

[2024-02-14 15:14:55] INFO: CheckM v1.2.2
[2024-02-14 15:14:55] INFO: checkm lineage_wf -x fasta /var/folders/nj/rfpdzc_90zl3555cttz236_w0000gp/T/qiime2/rischv/data/0a7a97fc-f0f3-462f-880b-66bc9d052fbc/data/sample1 /var/folders/nj/rfpdzc_90zl3555cttz236_w0000gp/T/tmpf022r1r3/results/samp
le1
[2024-02-14 15:14:55] INFO: CheckM data: /Users/rischv/Downloads/checkm_data_2015_01_16
[2024-02-14 15:14:55] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2024-02-14 15:14:56] INFO: Identifying marker genes in 2 bins with 1 threads:
[2024-02-14 15:15:07] INFO: Saving HMM info to file.
[2024-02-14 15:15:07] INFO: Calculating genome statistics for 2 bins with 1 threads:
[2024-02-14 15:15:07] INFO: Extracting marker genes to align.
[2024-02-14 15:15:07] INFO: Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 2 (50.00%) bins.^M    Finished parsing hits for 2 of 2 (100.00%) bins.^M[2024-02-14 15:15:07] INFO: Extracting 43 HMMs with 1 threads:

[2024-02-14 15:15:09] INFO: Aligning 43 marker genes with 1 threads:
[2024-02-14 15:15:11] ERROR: Make sure pplacer is on your system path.

  Controlled exit resulting from an unrecoverable error or warning.
Traceback (most recent call last):
  File "/Users/rischv/miniconda3/envs/checkm3/lib/python3.8/site-packages/q2cli/commands.py", line 478, in __call__
    results = self._execute_action(
  File "/Users/rischv/miniconda3/envs/checkm3/lib/python3.8/site-packages/q2cli/commands.py", line 539, in _execute_action
    results = action(**arguments)
  File "<decorator-gen-26>", line 2, in evaluate_bins
  File "/Users/rischv/miniconda3/envs/checkm3/lib/python3.8/site-packages/qiime2/sdk/action.py", line 342, in bound_callable
    outputs = self._callable_executor_(
  File "/Users/rischv/miniconda3/envs/checkm3/lib/python3.8/site-packages/qiime2/sdk/action.py", line 615, in _callable_executor_
    ret_val = self._callable(output_dir=temp_dir, **view_args)
  File "/Users/rischv/miniconda3/envs/checkm3/lib/python3.8/site-packages/q2_checkm/checkm.py", line 272, in evaluate_bins
    reports = _evaluate_bins(results_dir, bins, db_path, common_args)
  File "/Users/rischv/miniconda3/envs/checkm3/lib/python3.8/site-packages/q2_checkm/checkm.py", line 59, in _evaluate_bins
    run_command(cmd, env={**os.environ, "CHECKM_DATA_PATH": db_path})
  File "/Users/rischv/miniconda3/envs/checkm3/lib/python3.8/site-packages/q2_checkm/utils.py", line 28, in run_command
    subprocess.run(cmd, env=env, check=True)
  File "/Users/rischv/miniconda3/envs/checkm3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['checkm', 'lineage_wf', '-x', 'fasta', '/var/folders/nj/rfpdzc_90zl3555cttz236_w0000gp/T/qiime2/rischv/data/0a7a97fc-f0f3-462f-880b-66bc9d052fbc/data/sample1', '/var/folders/nj/rfpdzc_90zl3555cttz236_w0000gp/T/tmpf022r1r3/results/sample1']' returned non-zero exit status 1.

i have pplacer installed in my conda env with conda from the Metagenlab channel.
@misialq do you know  what the problem could be?

**Comment by misialq** [comment]
Hey @VinzentRisch, could you share the steps you followed to create this conda environment?

**Comment by misialq** [comment]
Hey @VinzentRisch, thanks for testing it out - I am unable to reproduce your problem. Could you maybe try to follow the installation instructions from the README? (I just updated those; you may need to modify a bit for Apple Silicon)

**Comment by misialq** [comment]
Also, could you please check out why the lint check fails and fix? 🙏

**Comment by misialq** [comment]
Oh, wait, actually it may just not work on _your_ Mac - I don't think pplacer is compiled for your architecture 😢 You may need to test it out on an Intel-backed device...

**Comment by VinzentRisch** [comment]
hi Michal
so i checked the lint problem and its this line
`# bool is a subclass of int so to only reject ints we need to do:
        if type(arg_val) != int and not arg_val:`
and the lint requests to change it to `if type(arg_val) is not int and not arg_val:`
But i'm not sure what you meant with the comment. Do you mean that you have to ignore the lint to get the behaviour that you want? Or is the comment not about that?

**Comment by VinzentRisch** [comment]
So I will try it again on euler to try the installation.

**Comment by misialq** [comment]
Hey @VinzentRisch, thanks for looking into that! I think what was meant by my comment was that since integers are a subclass of `bool` we need to do the exact match rather than use `isinstance`. I guess the linter just wants you to change the `!=` to `is not` to be explicit. So it should be fine to just apply that change :)

And 👍 for the Euler testing.

**Comment by misialq** [comment]
Hey @VinzentRisch, I just updated the CI workflow on the main branch to follow our newest convention - could you please update this branch to re-run the checks? 🙏

**Review by misialq — APPROVED** [review]
Hey @VinzentRisch, I tested it locally and all seemed ok - once you test on Euler, feek free to squash-merge. We can fix the CI afterwards as it is unrelated to this PR.

**Comment by VinzentRisch** [comment]
I created the env exactly how it is written in the readme except that i installed the pr branch and there is this error:

command: `qiime checkm evaluate-bins --i-bins /cluster/home/rischv/checkm/mags.qza --p-db-path /cluster/home/rischv/checkm/checkm_data_2015_01_16 --o-visualization /cluster/home/rischv/checkm/report.qzv`

pplacer is installed and also all the dependencies

Running external command line application(s). This may print messages to stdout and/or stderr.
The command(s) being run are below. These commands cannot be manually re-run as they will depend on temporary files that no longer exist.

Command: checkm lineage_wf -x fasta /tmp/qiime2/rischv/data/0a7a97fc-f0f3-462f-880b-66bc9d052fbc/data/sample1 /tmp/tmpe3ir6nyc/results/sample1

[2024-05-14 17:20:54] INFO: CheckM v1.2.2
[2024-05-14 17:20:54] INFO: checkm lineage_wf -x fasta /tmp/qiime2/rischv/data/0a7a97fc-f0f3-462f-880b-66bc9d052fbc/data/sample1 /tmp/tmpe3ir6nyc/results/sample1
[2024-05-14 17:20:54] INFO: CheckM data: /cluster/home/rischv/checkm/checkm_data_2015_01_16
[2024-05-14 17:20:54] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2024-05-14 17:20:54] INFO: Identifying marker genes in 2 bins with 1 threads:
    Finished processing 2 of 2 (100.00%) bins.
[2024-05-14 17:21:06] INFO: Saving HMM info to file.
[2024-05-14 17:21:06] INFO: Calculating genome statistics for 2 bins with 1 threads:
    Finished processing 2 of 2 (100.00%) bins.
[2024-05-14 17:21:06] INFO: Extracting marker genes to align.
[2024-05-14 17:21:06] INFO: Parsing HMM hits to marker genes:
[2024-05-14 17:21:06] INFO: Extracting 43 HMMs with 1 threads:

    Finished extracting 43 of 43 (100.00%) HMMs.
[2024-05-14 17:21:07] INFO: Aligning 43 marker genes with 1 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.
[2024-05-14 17:21:08] INFO: Reading marker alignment files.
[2024-05-14 17:21:08] INFO: Concatenating alignments.
[2024-05-14 17:21:08] INFO: Placing 2 bins into the genome tree with pplacer (be patient).
sh: line 1: 31677 Killed                  pplacer -j 1 -c /cluster/home/rischv/checkm/checkm_data_2015_01_16/genome_tree/genome_tree_full.refpkg -o /tmp/tmpe3ir6nyc/results/sample1/storage/tree/concatenated.pplacer.json /tmp/tmpe3ir6nyc/results/sample1/storage/tree/concatenated.fasta > /tmp/tmpe3ir6nyc/results/sample1/storage/tree/pplacer.out
Uncaught exception: Sys_error("/tmp/tmpe3ir6nyc/results/sample1/storage/tree/concatenated.pplacer.json: No such file or directory")
Fatal error: exception Sys_error("/tmp/tmpe3ir6nyc/results/sample1/storage/tree/concatenated.pplacer.json: No such file or directory")
[2024-05-14 17:22:20] INFO: { Current stage: 0:01:25.249 || Total: 0:01:25.249 }
[2024-05-14 17:22:20] INFO: [CheckM - lineage_set] Inferring lineage-specific marker sets.
[2024-05-14 17:22:20] INFO: Reading HMM info from file.
[2024-05-14 17:22:20] INFO: Parsing HMM hits to marker genes:
[2024-05-14 17:22:20] INFO: Determining marker sets for each genome bin.


Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/cluster/home/rischv/miniconda3/envs/qiime2-tiny-chekm/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/cluster/home/rischv/miniconda3/envs/qiime2-tiny-chekm/lib/python3.8/site-packages/checkm/main.py", line 980, in parseOptions
    self.lineageSet(options)
  File "/cluster/home/rischv/miniconda3/envs/qiime2-tiny-chekm/lib/python3.8/site-packages/checkm/main.py", line 261, in lineageSet
    treeParser.getBinMarkerSets(options.tree_dir, options.marker_file,
  File "/cluster/home/rischv/miniconda3/envs/qiime2-tiny-chekm/lib/python3.8/site-packages/checkm/treeParser.py", line 485, in getBinMarkerSets
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "/cluster/home/rischv/miniconda3/envs/qiime2-tiny-chekm/lib/python3.8/site-packages/dendropy/datamodel/basemodel.py", line 217, in get_from_path
    with open(src, *open_args) as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpe3ir6nyc/results/sample1/storage/tree/concatenated.tre'
Traceback (most recent call last):
  File "/cluster/home/rischv/miniconda3/envs/qiime2-tiny-chekm/lib/python3.8/site-packages/q2cli/commands.py", line 520, in __call__
    results = self._execute_action(
  File "/cluster/home/rischv/miniconda3/envs/qiime2-tiny-chekm/lib/python3.8/site-packages/q2cli/commands.py", line 581, in _execute_action
    results = action(**arguments)
  File "<decorator-gen-26>", line 2, in evaluate_bins
  File "/cluster/home/rischv/miniconda3/envs/qiime2-tiny-chekm/lib/python3.8/site-packages/qiime2/sdk/action.py", line 342, in bound_callable
    outputs = self._callable_executor_(
  File "/cluster/home/rischv/miniconda3/envs/qiime2-tiny-chekm/lib/python3.8/site-packages/qiime2/sdk/action.py", line 615, in _callable_executor_
    ret_val = self._callable(output_dir=temp_dir, **view_args)
  File "/cluster/home/rischv/repo/q2-checkm/q2_checkm/checkm.py", line 272, in evaluate_bins
    reports = _evaluate_bins(results_dir, bins, db_path, common_args)
  File "/cluster/home/rischv/repo/q2-checkm/q2_checkm/checkm.py", line 59, in _evaluate_bins
    run_command(cmd, env={**os.environ, "CHECKM_DATA_PATH": db_path})
  File "/cluster/home/rischv/repo/q2-checkm/q2_checkm/utils.py", line 28, in run_command
    subprocess.run(cmd, env=env, check=True)
  File "/cluster/home/rischv/miniconda3/envs/qiime2-tiny-chekm/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['checkm', 'lineage_wf', '-x', 'fasta', '/tmp/qiime2/rischv/data/0a7a97fc-f0f3-462f-880b-66bc9d052fbc/data/sample1', '/tmp/tmpe3ir6nyc/results/sample1']' returned non-zero exit status 1.


Ill see tomorrow if i can figure it out

**Comment by VinzentRisch** [comment]
Hi @misialq 
I dont know what the problem is. I tried again with different mags and with reinstalling the dependencies but there is the same error.

**Comment by misialq** [comment]
Hey @VinzentRisch, are you sure you gave enough memory to your job? I'm trying it now on Euler as well but it seems to be running fine. My command is slightly different, though:
```
qiime checkm evaluate-bins \
  --i-bins ./cache:mags \
  --p-threads 4 \
  --p-db-path $WORK/../DATABASES/CheckM \
  --p-pplacer-threads 4 \
  --p-reduced-tree \
  --verbose \ 
  --o-visualization mags.qzv
```
I requested 32GB for this one.

**Comment by misialq** [comment]
Awesome, thanks @VinzentRisch!

**Pull request merged**
